### ISSUE TITLE
Convert markdown to html from typescript code

### ISSUE THREAD

**Issue by clabnet** [juanelas/markdown-to-standalone-html#2]
I would convert a markdown to html code with this test code on a typescript project:
```
import markdownToStandAloneHtml from '../node_modules/markdown-to-standalone-html/dist/index'
it('should convert markdown to html standalone', async () => {
    const actual = await markdownToStandAloneHtml(fileContent,
      { here the options } )
    writeFile('cheatSheetStandalone.html', actual)
    // console.log(actual)
    const isFileExist = fileExists('cheatSheetStandalone.html')
    expect(isFileExist === true);
  });
  ```
  where `fileContent` is a valid markdown string.
  
  A couple of questions: 
  1) how to import without pass from node_modules folder
  2) I didn't quite understand how to pass `Options` . I have tried to create a custom html template :
  ```
  { basePath: "c:/temp", template: "c:/temp/template-simple.html", plugins: [] }
  ```
  but my custom template is not found.  
  Any help please ? Thank's

**Comment by juanelas** [comment]
It wasn't thought to be used programmatically, but now you can ;-).
Please update to the latest version (2.1.1).

- Question 1. Just `import markdownToStandAloneHtml from 'markdown-to-standalone-html`'
- Question 2. Generate two files `template-simple.html` and `template-simple.toc.html`. Take a look to `templates/template.html` (no toc version) and `templates/template.toc.html` (TOC version) for inspiration. Then `{ basePath: "c:\temp", template: "c:\temp\template-simple.html", plugins: [] }`

> Notice that you are disabling all plugins by default. If you want to know how to enable some of them, just take a look at `src/markdown-to-standalone-html.ts`
> Notice also  that `basePath` is the directory where relative links to local resources are computed (for example for local images), and it is not related to where the template is stored. It is likely that you don't need it (it defaults to where the .md input file is), so you likely just need options `{ template: "c:\temp\template.html" }`

Please tell me if your issue is solved so that I can close it.

**Comment by clabnet** [comment]
Thank's for your support.
